export const metadata = {
  title: 'Shop | Catalog',
  description: 'Generated by create next app',
};

const DinamikListLayout = ({ children }) => {
  return (
    <>
      <div>{children}</div>
    </>
  );
};

export default DinamikListLayout;
