'use client';
import Footer from '@/src/components/Footer/Footer';
import PartnersSlider from '@/src/components/PartnersSlider/PartnersSlider';
import ContactBlock from '@/src/components/ContactBlock/ContactBlock';
import PromoBlockAllPages from '@/src/components/PromoBlockAllPages/PromoBlockAllPages';
import { BcgContainer } from '@/src/components/CatalogList/CatalogList.styled';

export const metadata = {
  title: 'Shop | Offer',
  description: 'Generated by create next app',
};

const OfferLayout = ({ children }) => {
  return (
    <>
      <PromoBlockAllPages />
      <BcgContainer>{children}</BcgContainer>
      <ContactBlock />
      <PartnersSlider />
      <Footer />
    </>
  );
};

export default OfferLayout;
