import Footer from '@/src/components/Footer/Footer';
export const metadata = {
  title: 'Shop | Basket',
  description: 'Generated by create next app',
};

const BasketLayout = ({ children }) => {
  return (
    <>
      <div>{children}</div>
      <Footer />
    </>
  );
};

export default BasketLayout;
