import './globals.css';
import { Roboto } from 'next/font/google';
import Header from '../components/Header/Header';
import Head from 'next/head';

const roboto = Roboto({
  subsets: ['latin', 'cyrillic'],
  weight: ['300', '400', '500', '700', '900'],
});

export const metadata = {
  title: 'Shop | Home',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <body className={roboto.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
