export const metadata = {
  title: 'Shop | Products',
  description: 'Generated by create next app',
};

const ProductsLayout = ({ children }) => {
  return (
    <>
      <div>{children}</div>
    </>
  );
};

export default ProductsLayout;
